---
- name: This is a hello-world example
  hosts: all
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt

# Install system apt packages
- hosts: all
  become: yes
  tasks:
  - name: install packages
    apt: name={{item}} state=installed
    with_items:
      - tree         # Optional
      - python-pip   # Optional
      - python-dev   # Optional
      - python3-pip
      - python3-dev
      - nginx

# Install the app, note: don't do these tasks with become sudo
- hosts: webservers
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/AaronNBrock/message-board.git'
      dest: /home/{{ ansible_ssh_user }}/message-board
      update: yes  # Does a git pull if the repo already exists
  - name: install modules in a virtualenv
    pip:
      requirements: /home/{{ ansible_ssh_user }}/message-board/requirements.txt
      virtualenv: /home/{{ ansible_ssh_user }}/message-board/env
      virtualenv_python: python3.5

# # Configure app systemd service and nginx
# - hosts: all
#   become: yes
#   become_method: sudo
#   tasks:
#   - name: template systemd service config
#     copy:
#       src: .service
#       dest: /etc/systemd/system/{{ app_name }}.service
#   - name: start systemd app service
#     systemd: name={{ app_name }}.service state=restarted enabled=yes


# # Run a quick test to verify the site is working
# - hosts: all
#   tasks:
#   - name: get url
#     get_url:
#       url: http://{{inventory_hostname}}
#       dest: /tmp/index.html
#   - name: read html
#     shell: cat /tmp/index.html
#     register: html_contents
#   - name: check for string in html
#     when: html_contents.stdout.find('hello') != -1
#     debug: msg="success!"