---
- hosts: all
  vars:
    app_dir: /home/{{ ansible_ssh_user }}/message-board
  tasks:
  - name: install packages
    apt: name={{item}} state=present
    with_items:
      - python-pip   # Optional
      - python3-pip
      - python3-dev
      - python-virtualenv
    become: yes
  - name: clone repo
    git:
      repo: 'https://github.com/AaronNBrock/message-board.git'
      dest: '{{ app_dir }}'
      update: yes  # Does a git pull if the repo already exists
  - name: install modules in a virtualenv
    pip:
      requirements: '{{ app_dir }}/requirements.txt'
      virtualenv: '{{ app_dir }}/env'
      virtualenv_python: python3
  - name: template systemd service config
    copy:
      src: message-board.service
      dest: /etc/systemd/system/message-board.service
  - name: start systemd app service
    systemd: name={{ message-board }}.service state=restarted enabled=yes


# # Run a quick test to verify the site is working
# - hosts: all
#   tasks:
#   - name: get url
#     get_url:
#       url: http://{{inventory_hostname}}
#       dest: /tmp/index.html
#   - name: read html
#     shell: cat /tmp/index.html
#     register: html_contents
#   - name: check for string in html
#     when: html_contents.stdout.find('hello') != -1
#     debug: msg="success!"